services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=easy_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/easy_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
